title: "NYC FHV Fare Elasticity Project"
description: "An analytical deep dive into pricing dynamics for New York's high-volume for-hire vehicles."
theme: jekyll-theme-architect
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/AwesomeAnil/nyc-fhv-trip-miles-vs-trip-distance
